name: CD Pipeline

on:
    workflow_run:
      workflows: ["CI Pipeline"]
      types:
        - completed

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Conectar por SSH al host
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/Know_hosts
          ssh -T usuario@HOST
        env:
          HOST: ${{ secrets.SSH_HOST }}
          SSH_PROVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Extraer Imagen Docker
        run: sudo docker pull cesardw/cicd-pipeline:latest
  
      - name: Borrar Imagen Vieja
        run: sudo docker rm -f /cicd-pipeline-contenedor || true
  
      - name: Arrancar el Contenedor de Docker
        run: sudo docker run -d -p 8080:8080 --name /cicd-pipeline-contenedor cesardw/cicd-pipeline

        #self-hosted
