name: CD Pipeline

on:
    workflow_run:
      workflows: ["CI Pipeline"]
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest
    #self-hosted

    steps:  
      - name: Extraer Imagen Docker
        run: sudo docker pull cesardw/cicd-pipeline:latest
  
      - name: Borrar Imagen Vieja
        run: sudo docker rm -f cicd-pipeline-container || true
  
      - name: Arrancar el Contenedor de Docker
        run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container cesardw/cicd-pipeline